services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped

    ports:
      - "8081:80"     # HTTP
      - "8182:81"     # Admin UI
      - "4443:443"    # HTTPS

    volumes:
      - /volume1/docker/proxy/nginx-proxy-manager/data:/data
      - /volume1/docker/proxy/nginx-proxy-manager/letsencrypt:/etc/letsencrypt

    networks:
      - proxy

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped

    command: tunnel --no-autoupdate run --token INSERT_CLOUDFLARE_TUNNEL_TOKEN_HERE

    networks:
      - proxy

networks:
  proxy:
    name: proxy
    driver: bridge
